classin:
  api:
    url: https://api.eeo.cn
    register: /partner/api/course.api.php?action=register
    addSchoolStudent: /partner/api/course.api.php?action=addSchoolStudent
    addTeacher: /partner/api/course.api.php?action=addTeacher
    addCourse: /partner/api/course.api.php?action=addCourse
    createClass: /lms/activity/createClass
    updateClass: /lms/activity/updateClass
    createUnit: /lms/unit/create
    appId: 67402266
    appSecret: 1YqGfCpd