CREATE TABLE `edu_student` (
   `id`  bigint(20)   NOT NULL AUTO_INCREMENT     COMMENT 'ID',
  `name` varchar(50) NOT NULL COMMENT '学生姓名',
  `gender` varchar(10) DEFAULT 'male' COMMENT '性别（male-男 female-女）',
  `phone` varchar(20) DEFAULT NULL COMMENT '手机号码',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `register_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `agent_id` bigint(20) DEFAULT NULL COMMENT '所属代理的ID',
  `avatar` varchar(512) DEFAULT NULL COMMENT '头像地址',
  `password` varchar(100) NOT NULL COMMENT '密码',
  `remark` varchar(1024) DEFAULT NULL COMMENT '备注',
  `status`         tinyint(1)   UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态（1：启用；2：禁用）',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_user` bigint(20)   NOT NULL                    COMMENT '创建人',
  `update_user` bigint(20)   DEFAULT NULL                COMMENT '修改人',
  `institution_id` bigint(20) NOT NULL COMMENT '所属机构ID',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_student_institution` FOREIGN KEY (`institution_id`) REFERENCES `edu_institution` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='学生表';

ALTER TABLE `edu_student` AUTO_INCREMENT = 1;

CREATE TABLE `edu_teacher` (
   `id`  bigint(20)   NOT NULL AUTO_INCREMENT     COMMENT 'ID',
  `name` varchar(50) NOT NULL COMMENT '教师姓名',
   `score`  int NOT NULL DEFAULT 5  COMMENT '评分',
   `tags` varchar(100) DEFAULT NULL COMMENT '标签',
  `gender` varchar(50) DEFAULT 'female' COMMENT '性别（male, female）',
  `is_show` tinyint DEFAULT '1' COMMENT '是否展示（ 1-展示, 2-不展示）',
  `is_fixed` tinyint DEFAULT '1' COMMENT '是否固定（ 1-固定, 2-不固定）',
  `phone` varchar(20) DEFAULT NULL COMMENT '手机号码',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `avatar` varchar(512) DEFAULT NULL COMMENT '头像地址',
  `audio_url` varchar(512) DEFAULT NULL COMMENT '音频地址',
  `video_url` varchar(512) DEFAULT NULL COMMENT '视频地址',
  `brief_intro` varchar(256) DEFAULT NULL COMMENT '简介',
  `description` varchar(1024) DEFAULT NULL COMMENT '描述',
  `group_name` varchar(100) DEFAULT NULL COMMENT '所属组',
  `sort`        int          NOT NULL DEFAULT 999        COMMENT '排序',
  `status`         tinyint(1)   UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态（1：启用；2：禁用）',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_user` bigint(20)   NOT NULL                    COMMENT '创建人',
  `update_user` bigint(20)   DEFAULT NULL                COMMENT '修改人',
  `institution_id` bigint(20) NOT NULL COMMENT '所属机构ID',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_teacher_institution` FOREIGN KEY (`institution_id`) REFERENCES `edu_institution` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='教师表';

CREATE TABLE `edu_slot` (
   `id`  bigint(20)   NOT NULL AUTO_INCREMENT     COMMENT 'ID',
  `teacher_id` bigint(20) NOT NULL COMMENT '所属教师ID',
  `teacher_name` varchar(50) DEFAULT NULL COMMENT '教师名字',
  `start_date` varchar(8) NOT NULL COMMENT '开课日期（格式：YYYYMMDD）',
  `start_time` varchar(5) NOT NULL COMMENT '开课时间（格式：HH:MM）',
  `weekday` tinyint(1) NOT NULL COMMENT '星期几（1：周一；2：周二；3：周三；4：周四；5：周五；6：周六；7：周日）',
  `duration` int NOT NULL DEFAULT 25 COMMENT '课程时长（单位为分钟）',
  `is_online` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否在线教室（0：否；1：是）',
  `status`         tinyint(1)   UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态（1：启用；0：禁用）',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_user` bigint(20)   NOT NULL                    COMMENT '创建人',
  `update_user` bigint(20)   DEFAULT NULL                COMMENT '修改人',
  `institution_id` bigint(20) COMMENT '所属机构ID',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_course_teacher` FOREIGN KEY (`teacher_id`) REFERENCES `edu_teacher` (`id`),
  CONSTRAINT `fk_course_institution` FOREIGN KEY (`institution_id`) REFERENCES `edu_institution` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='课程表';

CREATE TABLE `edu_booking` (
   `id`  bigint(20)   NOT NULL AUTO_INCREMENT     COMMENT 'ID',
  `slot_id` bigint(20) NOT NULL COMMENT '所属课程ID',
  `start_date` varchar(8) NOT NULL COMMENT '开课日期（格式：YYYYMMDD）',
  `start_time` varchar(5) NOT NULL COMMENT '开课时间（格式：HH:MM）',
  `student_id` bigint(20) NOT NULL COMMENT '所属学生ID',
  `student_name` varchar(50) NOT NULL COMMENT '所属学生姓名',
  `phone` varchar(20) NOT NULL COMMENT '预约手机号',
  `card_id` bigint(20) DEFAULT NULL COMMENT '预约会员卡ID',
  `card_name` varchar(100) DEFAULT NULL COMMENT '预约会员卡名称',
  `operator_name` varchar(50) NOT NULL COMMENT '操作人名字',
  `operate_time` datetime NOT NULL COMMENT '操作时间',
  `material_id` bigint(20) DEFAULT NULL COMMENT '预约教材ID',
  `material_name` varchar(100) DEFAULT NULL COMMENT '预约教材名字',
  `lesson_name` varchar(100) DEFAULT NULL COMMENT '预约课节名字',
  `material_url` varchar(512) DEFAULT NULL COMMENT '预约教材链接',
  `remark` varchar(1024) DEFAULT NULL COMMENT '预约备注',
  `status`         tinyint(1)   UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态（1：启用；0：禁用）',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_user` bigint(20)   NOT NULL                    COMMENT '创建人',
  `update_user` bigint(20)   DEFAULT NULL                COMMENT '修改人',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_booking_slot` FOREIGN KEY (`slot_id`) REFERENCES `edu_slot` (`id`),
  CONSTRAINT `fk_booking_student` FOREIGN KEY (`student_id`) REFERENCES `edu_student` (`id`),
  CONSTRAINT `fk_booking_card` FOREIGN KEY (`card_id`) REFERENCES `edu_card` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='预约表';

CREATE TABLE `edu_card` (
   `id`  bigint(20)   NOT NULL AUTO_INCREMENT     COMMENT 'ID',
  `name` varchar(100) NOT NULL COMMENT '会员卡名称',
  `type` tinyint NOT NULL COMMENT '会员卡类型（1：次卡有限期；2：次卡无限期；3：储蓄卡有限期；4：储蓄卡无限期）',
  `is_online_sale` tinyint DEFAULT NULL DEFAULT 1 COMMENT '是否支持线上购卡（1：支持；0：不支持）',
  `available_count` int DEFAULT NULL COMMENT '可用次数',
  `available_day` int DEFAULT NULL COMMENT '有效天数',
  `available_balance` decimal(10,2) DEFAULT NULL COMMENT '可用余额',
  `is_agent_only` tinyint NOT NULL DEFAULT 0 COMMENT '是否仅代理可售（1：是；0：否）',
  `price` decimal(10,2) DEFAULT NULL COMMENT '代理售卖价格',
  `sort` INT NOT NULL DEFAULT 999 COMMENT '排序字段，值越小排序越靠前',
  `is_renewable` tinyint NOT NULL DEFAULT 0 COMMENT '是否可续费（1：是；0：否）',
  `renew_times` int DEFAULT NULL COMMENT '续费次数',
  `renew_days` int DEFAULT NULL COMMENT '续费天数',
  `renew_price` decimal(10,2) DEFAULT NULL COMMENT '续费价格',
  `status`         tinyint(1)   UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态（1：启用；0：禁用）',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_user` bigint(20)   NOT NULL                    COMMENT '创建人',
  `update_user` bigint(20)   DEFAULT NULL                COMMENT '修改人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='会员卡表';

CREATE TABLE `edu_institution` (
   `id`  bigint(20)   NOT NULL AUTO_INCREMENT     COMMENT 'ID',
   `name` varchar(100) NOT NULL COMMENT '机构名称',
   `sid` varchar(100) NOT NULL COMMENT '机构SID',
   `secret` varchar(100) NOT NULL COMMENT '机构SECRET',
   `status`         tinyint(1)   UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态（1：启用；2：禁用）',
   `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   `create_user` bigint(20)   NOT NULL                    COMMENT '创建人',
   `update_user` bigint(20)   DEFAULT NULL                COMMENT '修改人',
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='机构表';

CREATE TABLE `classin_user` (
    `id`  bigint(20)   NOT NULL AUTO_INCREMENT     COMMENT 'ID',
    `nickname` varchar(50) DEFAULT NULL COMMENT '昵称',
    `user_type` tinyint NOT NULL DEFAULT 0 COMMENT '成员类型（0：不是成员；1：学生；2：老师）',
    `uid` varchar(50) DEFAULT NULL COMMENT 'Classin唯一映射关系',
    `password` varchar(100) DEFAULT NULL COMMENT '密码',
    `telephone` varchar(20) DEFAULT NULL COMMENT '手机号',
    `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
    `student_id` bigint(20) DEFAULT NULL COMMENT '关联学生ID',
    `teacher_id` bigint(20) DEFAULT NULL COMMENT '关联教师ID',
    `classin_institution_id` bigint(20) NOT NULL COMMENT '关联Classin机构ID',
    `status`         tinyint(1)   UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态（1：启用；2：禁用）',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_user` bigint(20)   NOT NULL                    COMMENT '创建人',
    `update_user` bigint(20)   DEFAULT NULL                COMMENT '修改人',
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_classin_user_student` FOREIGN KEY (`student_id`) REFERENCES `edu_student` (`id`),
    CONSTRAINT `fk_classin_user_teacher` FOREIGN KEY (`teacher_id`) REFERENCES `edu_teacher` (`id`),
    CONSTRAINT `fk_classin_user_institution` FOREIGN KEY (`classin_institution_id`) REFERENCES `edu_institution` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Classin用户表';

CREATE TABLE `classin_course` (
  `id`  bigint(20)   NOT NULL AUTO_INCREMENT     COMMENT 'ID',
  `name` varchar(100) NOT NULL COMMENT '课程名称',
  `head_teacher_uid` varchar(50) DEFAULT NULL COMMENT '班主任UID',
  `course_id` bigint(20) NOT NULL COMMENT '课程ID',
  `status`         tinyint(1)   UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态（1：启用；2：禁用）',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_user` bigint(20)   NOT NULL                    COMMENT '创建人',
  `update_user` bigint(20)   DEFAULT NULL                COMMENT '修改人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Classin课程表';

CREATE TABLE `classin_course_mapping` (
  `id`  bigint(20)   NOT NULL AUTO_INCREMENT     COMMENT 'ID',
  `classin_course_id` bigint(20) NOT NULL COMMENT 'Classin课程ID',
  `student_classin_id` bigint(20) NOT NULL COMMENT '学生-Classin关联ID',
  `teacher_classin_id` bigint(20) NOT NULL COMMENT '教师-Classin关联ID',
  `student_name` varchar(50) NOT NULL COMMENT '学生姓名',
  `teacher_name` varchar(50) NOT NULL COMMENT '教师姓名',
  `student_uid` varchar(50) DEFAULT NULL COMMENT '学生UID',
  `teacher_uid` varchar(50) DEFAULT NULL COMMENT '教师UID',
  `status`         tinyint(1)   UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态（1：启用；2：禁用）',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_user` bigint(20)   NOT NULL                    COMMENT '创建人',
  `update_user` bigint(20)   DEFAULT NULL                COMMENT '修改人',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_classin_course_mapping_classin_course` FOREIGN KEY (`classin_course_id`) REFERENCES `classin_course` (`id`),
  CONSTRAINT `fk_classin_course_mapping_student_classin` FOREIGN KEY (`student_classin_id`) REFERENCES `edu_student_classin` (`id`),
  CONSTRAINT `fk_classin_course_mapping_teacher_classin` FOREIGN KEY (`teacher_classin_id`) REFERENCES `edu_teacher_classin` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Classin课程映射表';

-- 学生会员卡绑定表
CREATE TABLE `edu_stu_card` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `stu_id` bigint(20) NOT NULL COMMENT '学生ID',
  `stu_name` varchar(50) COMMENT '学生姓名',
  `card_id` bigint(20) NOT NULL COMMENT '会员卡ID',
  `card_name` varchar(100) NOT NULL COMMENT '会员卡名称',
  `card_type` tinyint NOT NULL COMMENT '会员卡类型（1：次卡有限期；2：次卡无限期；3：储蓄卡有限期；4：储蓄卡无限期）',
  `balance` decimal(10,2) NOT NULL DEFAULT 0 COMMENT '剩余次数/余额',
  `expire_date` date DEFAULT NULL COMMENT '到期日期',
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态（1：启用；0：禁用）',
  `card_status` tinyint(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '卡状态（1：启用，学生端可见；0：禁用，学生端不可见，后台管理系统可见）',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_user` bigint(20) NOT NULL COMMENT '创建人',
  `update_user` bigint(20) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_stu_card_student` FOREIGN KEY (`stu_id`) REFERENCES `edu_student` (`id`),
  CONSTRAINT `fk_stu_card_card` FOREIGN KEY (`card_id`) REFERENCES `edu_card` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='学生会员卡绑定表';

CREATE TABLE `edu_transaction` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `stu_card_id` bigint(20) NOT NULL COMMENT '学生会员卡绑定表ID',
  `stu_id` bigint(20) NOT NULL COMMENT '学生ID',
  `stu_name` varchar(50) COMMENT '学生姓名',
  `card_id` bigint(20) NOT NULL COMMENT '会员卡ID',
  `card_name` varchar(100) COMMENT '会员卡名称',
  `type` varchar(32) NOT NULL COMMENT '变动类型（credit:充值, debit:扣费, freeze:冻结, activate:激活, cancel:取消约课, bind:首次绑卡, book_debit:约课扣费）',
  `debit_amount` decimal(10,2) DEFAULT 0 COMMENT '支出金额（扣款）',
  `credit_amount` decimal(10,2) DEFAULT 0 COMMENT '收入金额（充值/收入）',
  `debit_days` int DEFAULT 0 COMMENT '减少有效期天数',
  `credit_days` int DEFAULT 0 COMMENT '增加有效期天数',
  `before_amount` decimal(10,2) DEFAULT 0 COMMENT '变动前余额/次数',
  `after_amount` decimal(10,2) DEFAULT 0 COMMENT '变动后余额/次数',
  `actual_amount` decimal(10,2) DEFAULT 0 COMMENT '实收金额',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_user` bigint(20) NOT NULL COMMENT '创建人',
  `update_user` bigint(20) DEFAULT NULL COMMENT '修改人',
  `operator_id` bigint(20) DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(50) DEFAULT NULL COMMENT '操作人姓名',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_transaction_stu_card` FOREIGN KEY (`stu_card_id`) REFERENCES `edu_stu_card` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='会员卡交易流水表';

CREATE TABLE `edu_salary` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `teacher_id` bigint(20) NOT NULL COMMENT '教师ID',
  `teacher_name` varchar(50) NOT NULL COMMENT '教师姓名',
  `start_date` date NOT NULL COMMENT '起始日期',
  `end_date` date NOT NULL COMMENT '结束日期',
  `course_count` int NOT NULL DEFAULT 0 COMMENT '课程总数',
  `course_amount` decimal(10,2) NOT NULL DEFAULT 0 COMMENT '课程总金额',
  `deduction_amount` decimal(10,2) NOT NULL DEFAULT 0 COMMENT '扣款金额',
  `tip_amount` decimal(10,2) NOT NULL DEFAULT 0 COMMENT '小费金额',
  `final_amount` decimal(10,2) NOT NULL DEFAULT 0 COMMENT '最终支付金额',
  `status` tinyint(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态（0：未结算；1：已结算）',
  `rate` int NOT NULL DEFAULT 0 COMMENT '单价',
  `group_name` varchar(100) DEFAULT NULL COMMENT '所属组',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_user` bigint(20) NOT NULL COMMENT '创建人',
  `update_user` bigint(20) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_teacher_salary_teacher` FOREIGN KEY (`teacher_id`) REFERENCES `edu_teacher` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='教师工资表';
